### ISSUE TITLE
what is autorisation the private app need 

### ISSUE THREAD

**Issue by alphaleadership** [dichternebel/voice-channel-grabber#2]

**Comment by dichternebel** [comment]
For an app there is no need to set scopes like for a bot. Once you start the app it will request for the permission to use RPC locally to be able to connect to your Discord client.
  

 Von: alphaleadership ***@***.***>Gesendet: Samstag, Juli 6, 2024 9:27 AMAn: dichternebel/voice-channel-grabber ***@***.***>Cc: Subscribed ***@***.***>Betreff: [dichternebel/voice-channel-grabber] what is autorisation the private app need (Issue #2)
