### ISSUE TITLE
Custom query options

### ISSUE THREAD

**Issue by francislavoie** [dichternebel/voice-channel-grabber#5]
I'm looking to help my streamer set this up.

I noticed that the URL query for the overlay is hard-coded here https://github.com/dichternebel/voice-channel-grabber/blob/75a8f1ca4bf2d8ab9c4703541d89b44105ed8636/Program.cs#L279 but I know that the streamer will want to be able to adjust the options away from this (e.g. always show all people in the call, instead of hiding inactive speakers).

I think the `?<query>` part should be made configurable.

**Comment by dichternebel** [comment]
Hi!
This is the default when the OBS Browser Source URL is empty. Just provide a valid URL with your query parameters and the app will use them.
https://github.com/dichternebel/voice-channel-grabber/blob/fbfda9fdc876f8e4e893c9d8254bb69ad5de837a/Program.cs#L298

**Comment by francislavoie** [comment]
Ah good! Thanks, and sorry, I really didn't put more than 30 seconds of effort at reading the code. Looks good!
